//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabio
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTASXLINEA
    {
        public int Codigo_cotlinea { get; set; }
        public int Cota_Cotlinea { get; set; }
        public Nullable<int> instrumento_cotlinea { get; set; }
        public Nullable<int> bm_cotlinea { get; set; }
        public Nullable<int> be_cotlinea { get; set; }
        public Nullable<int> ba_cotlinea { get; set; }
        public Nullable<int> br_cotlinea { get; set; }
    }
}
