//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabio
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBMODULOS
    {
        public int ID_SUBMODULO { get; set; }
        public string NOMBRE_SUBMOD { get; set; }
        public string SYS_NOM { get; set; }
        public Nullable<int> ID_MODULO { get; set; }
    
        public virtual MODULOS MODULOS { get; set; }
    }
}
